services:
  - type: web
    name: sea
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate
      gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-service.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://your-service.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: sea-db
          property: connectionString
databases:
  - name: sea-db
