# Generated by Django 5.2.6 on 2025-09-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('kayak', 'Kayak'), ('swim', 'Swim'), ('hike', 'Hike'), ('cycle', 'Cycle'), ('yoga', 'Yoga'), ('sauna', 'Mobile Sauna'), ('tour', 'Tour')], default='kayak', max_length=12)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
