# Generated by Django 5.2.6 on 2025-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='type',
            field=models.CharField(choices=[('kayak', 'Kayak'), ('swim', 'Swim'), ('hike', 'Hike'), ('cycle', 'Cycle'), ('sup', 'Stand Up Paddle'), ('sailing', 'Sailing'), ('yoga', 'Yoga'), ('sauna', 'Mobile Sauna'), ('tour', 'Tour'), ('tri', 'Triathlon')], default='kayak', max_length=12),
        ),
    ]
