# Generated by Django 5.2.6 on 2025-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_spot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='type',
            field=models.CharField(blank=True, choices=[('kayak', 'Kayak'), ('swim', 'Swim'), ('hike', 'Hike'), ('cycle', 'Cycle'), ('sup', 'Stand Up Paddle'), ('sailing', 'Sailing'), ('yoga', 'Yoga'), ('sauna', 'Mobile Sauna'), ('tour', 'Tour'), ('tri', 'Triathlon')], default='', max_length=20),
        ),
    ]
