# Generated by Django 5.2.6 on 2025-09-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0002_alter_spot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='spot',
            field=models.ForeignKey(blank=True, help_text='Where this activity happens.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.spot'),
        ),
    ]
