# Generated by Django 5.2.6 on 2025-09-15 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_spot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('user', 'activity', 'start_dt'), name='uniq_confirmed_booking_per_user_slot'),
        ),
    ]
