# Generated by Django 5.2.6 on 2025-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_booking_uniq_confirmed_booking_per_user_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/covers/'),
        ),
    ]
