# Generated by Django 5.2.6 on 2025-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='requires_booking',
            field=models.BooleanField(default=True, help_text='If off, no slots/booking are shown; page is informational only.'),
        ),
    ]
