# Generated by Django 5.2.6 on 2025-09-08 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuddySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('type', models.CharField(choices=[('swim', 'Swim'), ('kayak', 'Kayak'), ('hike', 'Hike'), ('cycle', 'Cycle')], default='swim', max_length=12)),
                ('start_dt', models.DateTimeField()),
                ('location_name', models.CharField(blank=True, default='', max_length=140)),
                ('lat', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('capacity', models.PositiveIntegerField(default=6)),
                ('status', models.CharField(default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_buddy_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='buddy_sessions', through='buddies.BuddyParticipant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
        migrations.AddField(
            model_name='buddyparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddies.buddysession'),
        ),
        migrations.CreateModel(
            name='BuddyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='buddies.buddysession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='buddyparticipant',
            unique_together={('session', 'user')},
        ),
    ]
