--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-10-02 18:02:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 26487)
-- Name: activities_activity; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.activities_activity (
    id bigint NOT NULL,
    title character varying(160) NOT NULL,
    description text NOT NULL,
    price numeric(8,2) NOT NULL,
    duration_minutes integer NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    provider_id bigint NOT NULL,
    spot_id bigint,
    image character varying(100),
    requires_booking boolean NOT NULL,
    CONSTRAINT activities_activity_capacity_check CHECK ((capacity >= 0)),
    CONSTRAINT activities_activity_duration_minutes_check CHECK ((duration_minutes >= 0))
);


ALTER TABLE public.activities_activity OWNER TO sea_user;

--
-- TOC entry 237 (class 1259 OID 26486)
-- Name: activities_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.activities_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 26629)
-- Name: activities_activityrsvp; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.activities_activityrsvp (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    activity_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.activities_activityrsvp OWNER TO sea_user;

--
-- TOC entry 250 (class 1259 OID 26628)
-- Name: activities_activityrsvp_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.activities_activityrsvp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_activityrsvp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 26497)
-- Name: activities_booking; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.activities_booking (
    id bigint NOT NULL,
    start_dt timestamp with time zone NOT NULL,
    party_size integer NOT NULL,
    status character varying(12) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    activity_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT activities_booking_party_size_check CHECK ((party_size >= 0))
);


ALTER TABLE public.activities_booking OWNER TO sea_user;

--
-- TOC entry 239 (class 1259 OID 26496)
-- Name: activities_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.activities_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 26481)
-- Name: activities_provider; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.activities_provider (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    contact_email character varying(254) NOT NULL
);


ALTER TABLE public.activities_provider OWNER TO sea_user;

--
-- TOC entry 235 (class 1259 OID 26480)
-- Name: activities_provider_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.activities_provider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_provider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 26387)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO sea_user;

--
-- TOC entry 223 (class 1259 OID 26386)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 26395)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO sea_user;

--
-- TOC entry 225 (class 1259 OID 26394)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 26381)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO sea_user;

--
-- TOC entry 221 (class 1259 OID 26380)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 26401)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO sea_user;

--
-- TOC entry 230 (class 1259 OID 26409)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO sea_user;

--
-- TOC entry 229 (class 1259 OID 26408)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 26400)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 26415)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO sea_user;

--
-- TOC entry 231 (class 1259 OID 26414)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 26577)
-- Name: buddies_buddymessage; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.buddies_buddymessage (
    id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    session_id bigint NOT NULL
);


ALTER TABLE public.buddies_buddymessage OWNER TO sea_user;

--
-- TOC entry 247 (class 1259 OID 26576)
-- Name: buddies_buddymessage_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.buddies_buddymessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buddies_buddymessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 26559)
-- Name: buddies_buddyparticipant; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.buddies_buddyparticipant (
    id bigint NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    session_id bigint NOT NULL
);


ALTER TABLE public.buddies_buddyparticipant OWNER TO sea_user;

--
-- TOC entry 243 (class 1259 OID 26558)
-- Name: buddies_buddyparticipant_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.buddies_buddyparticipant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buddies_buddyparticipant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 26565)
-- Name: buddies_buddysession; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.buddies_buddysession (
    id bigint NOT NULL,
    title character varying(140) NOT NULL,
    type character varying(12) NOT NULL,
    start_dt timestamp with time zone NOT NULL,
    location_name character varying(140) NOT NULL,
    lat numeric(8,5),
    lon numeric(8,5),
    capacity integer NOT NULL,
    status character varying(12) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    creator_id integer NOT NULL,
    created_by_id integer,
    CONSTRAINT buddies_buddysession_capacity_check CHECK ((capacity >= 0))
);


ALTER TABLE public.buddies_buddysession OWNER TO sea_user;

--
-- TOC entry 245 (class 1259 OID 26564)
-- Name: buddies_buddysession_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.buddies_buddysession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buddies_buddysession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 26473)
-- Name: core_spot; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.core_spot (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    type character varying(20) NOT NULL,
    lat numeric(8,5) NOT NULL,
    lon numeric(8,5) NOT NULL,
    is_active boolean NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_spot OWNER TO sea_user;

--
-- TOC entry 233 (class 1259 OID 26472)
-- Name: core_spot_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.core_spot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_spot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 26530)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO sea_user;

--
-- TOC entry 241 (class 1259 OID 26529)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 26373)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO sea_user;

--
-- TOC entry 219 (class 1259 OID 26372)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 26365)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO sea_user;

--
-- TOC entry 217 (class 1259 OID 26364)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: sea_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 26617)
-- Name: django_session; Type: TABLE; Schema: public; Owner: sea_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO sea_user;

--
-- TOC entry 4774 (class 2606 OID 26495)
-- Name: activities_activity activities_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_activity
    ADD CONSTRAINT activities_activity_pkey PRIMARY KEY (id);


--
-- TOC entry 4807 (class 2606 OID 26633)
-- Name: activities_activityrsvp activities_activityrsvp_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_activityrsvp
    ADD CONSTRAINT activities_activityrsvp_pkey PRIMARY KEY (id);


--
-- TOC entry 4780 (class 2606 OID 26502)
-- Name: activities_booking activities_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_booking
    ADD CONSTRAINT activities_booking_pkey PRIMARY KEY (id);


--
-- TOC entry 4772 (class 2606 OID 26485)
-- Name: activities_provider activities_provider_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_provider
    ADD CONSTRAINT activities_provider_pkey PRIMARY KEY (id);


--
-- TOC entry 4743 (class 2606 OID 26556)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4748 (class 2606 OID 26430)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4751 (class 2606 OID 26399)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4745 (class 2606 OID 26391)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4738 (class 2606 OID 26421)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4740 (class 2606 OID 26385)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4759 (class 2606 OID 26413)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4762 (class 2606 OID 26445)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4753 (class 2606 OID 26405)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4765 (class 2606 OID 26419)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4768 (class 2606 OID 26459)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4756 (class 2606 OID 26551)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4798 (class 2606 OID 26583)
-- Name: buddies_buddymessage buddies_buddymessage_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddymessage
    ADD CONSTRAINT buddies_buddymessage_pkey PRIMARY KEY (id);


--
-- TOC entry 4788 (class 2606 OID 26563)
-- Name: buddies_buddyparticipant buddies_buddyparticipant_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddyparticipant
    ADD CONSTRAINT buddies_buddyparticipant_pkey PRIMARY KEY (id);


--
-- TOC entry 4791 (class 2606 OID 26585)
-- Name: buddies_buddyparticipant buddies_buddyparticipant_session_id_user_id_f059cbb1_uniq; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddyparticipant
    ADD CONSTRAINT buddies_buddyparticipant_session_id_user_id_f059cbb1_uniq UNIQUE (session_id, user_id);


--
-- TOC entry 4796 (class 2606 OID 26570)
-- Name: buddies_buddysession buddies_buddysession_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddysession
    ADD CONSTRAINT buddies_buddysession_pkey PRIMARY KEY (id);


--
-- TOC entry 4770 (class 2606 OID 26479)
-- Name: core_spot core_spot_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.core_spot
    ADD CONSTRAINT core_spot_pkey PRIMARY KEY (id);


--
-- TOC entry 4785 (class 2606 OID 26537)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4733 (class 2606 OID 26379)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4735 (class 2606 OID 26377)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4731 (class 2606 OID 26371)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4803 (class 2606 OID 26623)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4810 (class 2606 OID 26635)
-- Name: activities_activityrsvp uniq_rsvp_per_activity; Type: CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_activityrsvp
    ADD CONSTRAINT uniq_rsvp_per_activity UNIQUE (user_id, activity_id);


--
-- TOC entry 4777 (class 1259 OID 26521)
-- Name: activities__start_d_7e7ec7_idx; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX activities__start_d_7e7ec7_idx ON public.activities_booking USING btree (start_dt);


--
-- TOC entry 4775 (class 1259 OID 26508)
-- Name: activities_activity_provider_id_285c861b; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX activities_activity_provider_id_285c861b ON public.activities_activity USING btree (provider_id);


--
-- TOC entry 4776 (class 1259 OID 26527)
-- Name: activities_activity_spot_id_5671f52f; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX activities_activity_spot_id_5671f52f ON public.activities_activity USING btree (spot_id);


--
-- TOC entry 4805 (class 1259 OID 26646)
-- Name: activities_activityrsvp_activity_id_b16e6f43; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX activities_activityrsvp_activity_id_b16e6f43 ON public.activities_activityrsvp USING btree (activity_id);


--
-- TOC entry 4808 (class 1259 OID 26647)
-- Name: activities_activityrsvp_user_id_7dade286; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX activities_activityrsvp_user_id_7dade286 ON public.activities_activityrsvp USING btree (user_id);


--
-- TOC entry 4778 (class 1259 OID 26519)
-- Name: activities_booking_activity_id_d83f9713; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX activities_booking_activity_id_d83f9713 ON public.activities_booking USING btree (activity_id);


--
-- TOC entry 4781 (class 1259 OID 26520)
-- Name: activities_booking_user_id_1c02f76b; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX activities_booking_user_id_1c02f76b ON public.activities_booking USING btree (user_id);


--
-- TOC entry 4741 (class 1259 OID 26557)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4746 (class 1259 OID 26441)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4749 (class 1259 OID 26442)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4736 (class 1259 OID 26427)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4757 (class 1259 OID 26457)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4760 (class 1259 OID 26456)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4763 (class 1259 OID 26471)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4766 (class 1259 OID 26470)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4754 (class 1259 OID 26552)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4799 (class 1259 OID 26610)
-- Name: buddies_buddymessage_session_id_1bcb4d8a; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX buddies_buddymessage_session_id_1bcb4d8a ON public.buddies_buddymessage USING btree (session_id);


--
-- TOC entry 4800 (class 1259 OID 26609)
-- Name: buddies_buddymessage_user_id_52a99460; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX buddies_buddymessage_user_id_52a99460 ON public.buddies_buddymessage USING btree (user_id);


--
-- TOC entry 4789 (class 1259 OID 26598)
-- Name: buddies_buddyparticipant_session_id_4f50b90e; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX buddies_buddyparticipant_session_id_4f50b90e ON public.buddies_buddyparticipant USING btree (session_id);


--
-- TOC entry 4792 (class 1259 OID 26591)
-- Name: buddies_buddyparticipant_user_id_e1cad7d8; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX buddies_buddyparticipant_user_id_e1cad7d8 ON public.buddies_buddyparticipant USING btree (user_id);


--
-- TOC entry 4793 (class 1259 OID 26616)
-- Name: buddies_buddysession_created_by_id_464e4fad; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX buddies_buddysession_created_by_id_464e4fad ON public.buddies_buddysession USING btree (created_by_id);


--
-- TOC entry 4794 (class 1259 OID 26597)
-- Name: buddies_buddysession_creator_id_621f52da; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX buddies_buddysession_creator_id_621f52da ON public.buddies_buddysession USING btree (creator_id);


--
-- TOC entry 4783 (class 1259 OID 26548)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4786 (class 1259 OID 26549)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4801 (class 1259 OID 26625)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4804 (class 1259 OID 26624)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4782 (class 1259 OID 26528)
-- Name: uniq_confirmed_booking_per_user_slot; Type: INDEX; Schema: public; Owner: sea_user
--

CREATE UNIQUE INDEX uniq_confirmed_booking_per_user_slot ON public.activities_booking USING btree (user_id, activity_id, start_dt) WHERE ((status)::text = 'confirmed'::text);


--
-- TOC entry 4818 (class 2606 OID 26503)
-- Name: activities_activity activities_activity_provider_id_285c861b_fk_activitie; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_activity
    ADD CONSTRAINT activities_activity_provider_id_285c861b_fk_activitie FOREIGN KEY (provider_id) REFERENCES public.activities_provider(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4819 (class 2606 OID 26522)
-- Name: activities_activity activities_activity_spot_id_5671f52f_fk_core_spot_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_activity
    ADD CONSTRAINT activities_activity_spot_id_5671f52f_fk_core_spot_id FOREIGN KEY (spot_id) REFERENCES public.core_spot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4830 (class 2606 OID 26636)
-- Name: activities_activityrsvp activities_activityr_activity_id_b16e6f43_fk_activitie; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_activityrsvp
    ADD CONSTRAINT activities_activityr_activity_id_b16e6f43_fk_activitie FOREIGN KEY (activity_id) REFERENCES public.activities_activity(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4831 (class 2606 OID 26641)
-- Name: activities_activityrsvp activities_activityrsvp_user_id_7dade286_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_activityrsvp
    ADD CONSTRAINT activities_activityrsvp_user_id_7dade286_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4820 (class 2606 OID 26509)
-- Name: activities_booking activities_booking_activity_id_d83f9713_fk_activitie; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_booking
    ADD CONSTRAINT activities_booking_activity_id_d83f9713_fk_activitie FOREIGN KEY (activity_id) REFERENCES public.activities_activity(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4821 (class 2606 OID 26514)
-- Name: activities_booking activities_booking_user_id_1c02f76b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.activities_booking
    ADD CONSTRAINT activities_booking_user_id_1c02f76b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4812 (class 2606 OID 26436)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4813 (class 2606 OID 26431)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4811 (class 2606 OID 26422)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4814 (class 2606 OID 26451)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4815 (class 2606 OID 26446)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4816 (class 2606 OID 26465)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4817 (class 2606 OID 26460)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4828 (class 2606 OID 26604)
-- Name: buddies_buddymessage buddies_buddymessage_session_id_1bcb4d8a_fk_buddies_b; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddymessage
    ADD CONSTRAINT buddies_buddymessage_session_id_1bcb4d8a_fk_buddies_b FOREIGN KEY (session_id) REFERENCES public.buddies_buddysession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4829 (class 2606 OID 26599)
-- Name: buddies_buddymessage buddies_buddymessage_user_id_52a99460_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddymessage
    ADD CONSTRAINT buddies_buddymessage_user_id_52a99460_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4824 (class 2606 OID 26571)
-- Name: buddies_buddyparticipant buddies_buddypartici_session_id_4f50b90e_fk_buddies_b; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddyparticipant
    ADD CONSTRAINT buddies_buddypartici_session_id_4f50b90e_fk_buddies_b FOREIGN KEY (session_id) REFERENCES public.buddies_buddysession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4825 (class 2606 OID 26586)
-- Name: buddies_buddyparticipant buddies_buddyparticipant_user_id_e1cad7d8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddyparticipant
    ADD CONSTRAINT buddies_buddyparticipant_user_id_e1cad7d8_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4826 (class 2606 OID 26611)
-- Name: buddies_buddysession buddies_buddysession_created_by_id_464e4fad_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddysession
    ADD CONSTRAINT buddies_buddysession_created_by_id_464e4fad_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4827 (class 2606 OID 26592)
-- Name: buddies_buddysession buddies_buddysession_creator_id_621f52da_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.buddies_buddysession
    ADD CONSTRAINT buddies_buddysession_creator_id_621f52da_fk_auth_user_id FOREIGN KEY (creator_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4822 (class 2606 OID 26538)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4823 (class 2606 OID 26543)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sea_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4982 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO sea_user;


-- Completed on 2025-10-02 18:02:22

--
-- PostgreSQL database dump complete
--

